---
apiVersion: v1
kind: Namespace
metadata:
  name: db-ns

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: db-ns
  labels:
    app: db
spec:
  accessModes:
  - ReadWriteOnce
  #- ReadOnlyMany # NFS type
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi # DigitalOcean smallest disk

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: db-ns
  labels: 
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      name: db-po
  template:
    metadata:
      name: db-po
      labels:
        app: db
        name: db-po
    spec:
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: db-pvc
      containers:
      - name: db-container
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeit
        volumeMounts:
        - name: data-vol
          mountPath: /var/lib/mysql