---
apiVersion: v1
kind: ConfigMap
metadata:
  name: htmls
  labels:
    app: webserver
data:
  index.html: |
    <h1><code>Hello World</code></h1>
  about.html: |
    <h1>About Me</h1>

---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  volumes:
  - name: html-vol
    configMap:
      name: htmls
  - name: tmp-vol
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx:1.25
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-vol
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: tmp-vol
      mountPath: /opt/tmp
