version: '3'

services:
  myapp:
    image: stackupiss/northwind-app:v1
    ports:
      - 8080:3000
    environment:
      - DB_USER=root
      - DB_HOST=mydb
      - DB_PASSWORD=changeit
    networks:
      - mynet

  mydb:
    image: stackupiss/northwind-db:v1
    volumes:
      - myvol:/var/lib/mysql
    networks:
      - mynet

networks:
  mynet:

volumes:
  myvol:
